export const passwordresetConfirmtypes ={
    PASSWORDRESETCONFIRM_REQUEST : 'PASSWORDRESETCONFIRM_REQUEST',
    PASSWORDRESETCONFIRM_SUCCESS : 'PASSWORDRESETCONFIRM_SUCCESS',
    PASSWORDRESETCONFIRM_FAIL : 'PASSWORDRESETCONFIRM_FAIL',
}